kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cep-cinder-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 9Gi # pass here the size of the volume
  storageClassName: cep-cinder-sc