apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-nfs
spec:
  selector: 
    matchLabels:
     app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs
            name: cep-nfs-vol
        ports:
        - containerPort: 80
      volumes:
        - name: cep-nfs-vol
          persistentVolumeClaim:
            claimName: cep-nfs-pvc