apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-vol
spec:
  selector: 
    matchLabels:
     app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: cep-nfs-vol
        ports:
        - containerPort: 80
      volumes:
        - name: cep-nfs-vol
          persistentVolumeClaim:
            claimName: cep-nfs-pvc