apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cep-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: cep-nfs-pv