apiVersion: v1
kind: Pod
metadata:
  name: hostPathContainer
spec:
  containers:
  - image: httpd
    name: apache-hostPath
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs/
      name: myvolume
  volumes:
  - name: myvolume
    hostPath:
      type: Directory
      path: /data/pv