apiVersion: v1
kind: Pod
metadata:
  name: mysql-con-secrets
spec:
  containers:
  - name: mysql-con-secrets
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysqlpassword
          key: password
    ports:
    - containerPort: 3306
