apiVersion: v1
kind: Pod
metadata:
  name: mysql-sin-secrets
spec:
  containers:
  - name: mysql-sin-secrets
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    ports:
    - containerPort: 3306
