apiVersion: apps/v1
kind: Deployment
metadata:
  name: initdb
spec:
  selector: 
    matchLabels:
     app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlpassword
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: workdir
          mountPath: /docker-entrypoint-initdb.d
      initContainers:
      - name: install
        image: busybox
        env:
        - name: SQLSOURCE
          valueFrom:
            configMapKeyRef:
              name: initsqlsource
              key: source
        command:
        - wget
        - "-O"
        - "/work-dir/init.sql"
        args: ["$(SQLSOURCE)"]
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      dnsPolicy: Default
      volumes:
      - name: workdir
        emptyDir: {}